Enchants:
  ice_aspect:
    display: 'Ice Aspect'
    type: MELEE
    trigger: DAMAGE
    max-level: 2
    mechanics:
      - SLOWNESS
  poison_touch:
    display: 'Poison Touch'
    type: MELEE
    trigger: DAMAGE
    max-level: 2
    mechanics:
      - POISON


Mechanics:
  SLOWNESS:
    type: POTION
    effect: SLOW level*3 0 Target
  POISON:
    type: POTION
    effect: POISON level*2 level-1 Target

