name: CustomizableEnchants
version: 1.0-SNAPSHOT
author: Mira
api-version: 1.16
main: com.mira.customizableenchants.CustomizableEnchants
description: Allows you to make your own enchants.

commands:
  customizableenchants:
    description: Main command of the Plugin.
    aliases: ce
    permission: customizableenchants.*

permissions:
  customizableenchants.*:
    default: op